# TFit Output Parameters

When run, TFit outputs a file in the format *_K_Models_MLE.tsv, which contains a series of parameters. The output is formatted as:

- Single line of:
```
ID|chrom:start-stop|forward coverage, reverse coverage
```
- Multiple lines of:
```
model complexity, log_likelihood \
mu_k sigma_k lambda_k pi_k fp_k w_[p,k],w_[f,k],w_[r,k], b_[f,k] a_[r,k]
```

## Parameter Descriptions

- $\sim\text{INT}$: Placed at the start of the output line, this variable represents the model complexity level for the given output parameters.
- $\mu_k$: Predicted Center of Bidir Transcription (Roughly the TSS)
- $\sigma_k$: Variance in $\mu$.
- $\lambda_k$: Entry Length (Initiation Distance)
- $\pi_k$: Strand Bias
- $fp_k$: Footprint (the distance between bidir peaks) 
- $w$: Mixture model weights (these are analagous to pausing ratios)
  - $w_{[p,k]}: Bidir Weight
  - $w_{[f,k]}: Forward Weight
  - $w_{[r,k]}: Reverse Weight
  - LI/EL Weights
- $l_s = \{l_+,l_-\}$: Predicted elongation components
  - $l_+ = b$: Positive Strand Termination
  - $l_- = a$: Negative Strand Termination
    
- TPM / FPKM for transcriptional activity (uniform alone)
  - Mu, a, b to bedfile
    - C-f, C-b
  - Calculate the weight - code for mary
- Large table of genes/parameters (incl expression level)
  - Sort parameters to find errors
- Dot size/alpha corresponds to expression level.
